// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/attach/upload": {
            "post": {
                "tags": [
                    "信息模块"
                ],
                "summary": "发送图片",
                "responses": {}
            }
        },
        "/contact/LoadCommunity": {
            "post": {
                "tags": [
                    "群模块"
                ],
                "summary": "加载群列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "群名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/contact/createCommunity": {
            "post": {
                "tags": [
                    "群模块"
                ],
                "summary": "新建群",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "ownerId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "群名称",
                        "name": "name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deleteRedisMsg": {
            "post": {
                "tags": [
                    "信息模块"
                ],
                "summary": "读取Redis信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户A_id",
                        "name": "userIdA",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户B_id",
                        "name": "userIdB",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "删除记录数目",
                        "name": "nums",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/getRedisMsg": {
            "post": {
                "tags": [
                    "信息模块"
                ],
                "summary": "读取Redis信息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户A_id",
                        "name": "userIdA",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "用户B_id",
                        "name": "userIdB",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/index": {
            "get": {
                "tags": [
                    "首页"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/msg/sendMsg": {
            "get": {
                "tags": [
                    "信息模块"
                ],
                "summary": "发送信息",
                "responses": {}
            }
        },
        "/msg/sendUserMsg": {
            "get": {
                "tags": [
                    "信息模块"
                ],
                "summary": "发送用户信息",
                "responses": {}
            }
        },
        "/toChat": {
            "get": {
                "tags": [
                    "首页"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/toRegister": {
            "get": {
                "tags": [
                    "首页"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/AddFriends": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "添加好友",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "添加用户id",
                        "name": "targetId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/createUser": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "新增用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "确认密码",
                        "name": "Identity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/deleteUser": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "删除用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/getUserList": {
            "get": {
                "tags": [
                    "用户模块"
                ],
                "summary": "获取所有用户信息",
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/loginByNameAndPwd": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户名",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "密码",
                        "name": "password",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "确认密码",
                        "name": "repassword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/searchFriends": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "查询好友列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "用户id",
                        "name": "userId",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/updateUser": {
            "post": {
                "tags": [
                    "用户模块"
                ],
                "summary": "修改用户",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "name",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "password",
                        "name": "password",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "phone",
                        "name": "phone",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "email",
                        "name": "email",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "code\",\"msg\",\"data“}",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
